use electoralbonddata;
show tables;
SELECT * FROM bonddata;
SELECT * FROM donordata;
SELECT * FROM receiverdata;
SELECT * FROM bankdata;

/******1. to Find out how much donors spent on bonds***/


select sum( denomination) as money from donordata as d
left join bonddata as b
using(unique_key);

#121555132000 money spend by the donor

 /****2.Find out total fund politicians got***/
SELECT SUM(Denomination) AS "Total_Fund_politicans_got" FROM  bonddata AS b 
 join receiverdata AS r
ON b.Unique_key=r.Unique_key
;
SELECT COUNT(Denomination) AS "Total_no_of_denominations "FROM bonddata;
## There are 20551 denominations are regestered in the bond data. out of 20551 there are only 
# 20421 bonds are being utilized by the politiciens and rest of the bonds are  not exercised.

/* 3. Find out the total amount of unaccounted money received by parties  ****/
SELECT SUM(Denomination) AS "Unaccounted_money" FROM bonddata AS b  
right join receiverdata AS r 
ON b.Unique_key=r.Unique_key
WHERE AccountNum is  Null;


SELECT SUM(DENOMINATION) AS UNACCOUNTED_MONEY FROM bonddata 
WHERE Unique_key IN (
SELECT R.Unique_key FROM donordata AS D
RIGHT JOIN receiverdata AS R
ON D.Unique_key=R.Unique_key
WHERE D.Unique_key IS NULL);

## 6232110000 MONEY IS SPEND AS UNACCOUNTED.

/* 4. Find year wise how much money is spend on bonds*/
SELECT YEAR(DateEncashment) AS "year",SUM(Denomination) AS "TOTAL_DENOMINATION" FROM bonddata AS B 
RIGHT JOIN receiverdata AS R 
ON B.Unique_key=R.Unique_key
GROUP BY YEAR(DateEncashment)
order by YEAR(DateEncashment);

/*5. In which month most amount is spent on bonds */
SELECT * FROM donordata;
SELECT * FROM bonddata;

WITH TOTAL AS (
SELECT DISTINCT( MONTHNAME (PURCHASEdATE)) AS "MONTH", SUM(Denomination) AS TOTAL_DENOMINATIONS FROM donordata AS D
LEFT JOIN bonddata AS B
ON D.Unique_key= B.Unique_key
GROUP BY MONTH)
SELECT  * FROM TOTAL
WHERE TOTAL_DENOMINATIONS =(SELECT MAX(TOTAL_DENOMINATIONS) FROM TOTAL);

## APRIL MONTH HAVE HIGHEST PURCHASE OF BONDS.

/* 6. Find out which company bought the highest number of bonds.*/
SELECT * FROM donordata;
WITH K as ( 
SELECT DISTINCT( Purchaser),COUNT(Purchaser)AS "NO_OF_BONDS"FROM donordata AS D
LEFT JOIN bonddata AS B
ON D.Unique_key=B.Unique_key
GROUP BY Purchaser)
SELECT * FROM K
WHERE NO_OF_BONDS =(SELECT MAX(NO_OF_BONDS) FROM K);

# FUTURE GAMING AND HOTEL SERVICES PRIVATE LIMITED BOUGHT HIGHEST NUMBER OF BONDS WITH 1368

/*7. Find out which company spent the most on electoral bonds.*/


WITH MONEY AS (
SELECT  DISTINCT(Purchaser), SUM(Denomination) AS "MONEY_SPEND" FROM donordata AS D 
LEFT JOIN bonddata AS B
USING(UNIQUE_KEY)
GROUP BY PURCHASER )
SELECT * FROM MONEY 
WHERE MONEY_SPEND=(SELECT MAX(MONEY_SPEND) FROM MONEY);




/* 8. List companies which paid the least to political parties.*/

WITH MONEY AS (
SELECT  DISTINCT(Purchaser), SUM(Denomination) AS "MONEY_SPEND",Unique_key FROM donordata AS D 
LEFT JOIN bonddata AS B
USING(UNIQUE_KEY)
GROUP BY PURCHASER,Unique_key ),
MONEY1 AS (SELECT  DISTINCT(PARTYNAME),Unique_key FROM receiverdata AS R),
MONEY0 AS (
SELECT * FROM MONEY AS M 
JOIN MONEY1 AS M1
USING(UNIQUE_KEY)),

MONEY2 AS (SELECT  PURCHASER,SUM(MONEY_SPEND)As CASH
 FROM MONEY0
 WHERE PARTYNAME IN (SELECT DISTINCT(PARTYNAME) FROM MONEY0)
 GROUP BY PURCHASER),
 MONEY3 AS (
 SELECT PURCHASER, CASH FROM MONEY2
 WHERE CASH= (SELECT MIN(CASH) FROM MONEY2)
 GROUP BY PURCHASER)
 SELECT * FROM MONEY3;

 
 
 
 
/*9. Which political party received the highest cash?*/
SELECT * FROM receiverdata;
SELECT * FROM bonddata;

#USING CTE's
 WITH MAXDATA AS (
SELECT PartyName, SUM(DENOMINATION) AS TOTAL_DENOMINATIONS
 FROM receiverdata AS R
LEFT JOIN bonddata AS B
USING(Unique_key)
GROUP BY PARTYNAME
)
SELECT * FROM MAXDATA
WHERE TOTAL_DENOMINATIONS= (SELECT MAX(TOTAL_DENOMINATIONS) FROM MAXDATA
);

#USING SUB-QUERIES
SELECT * FROM receiverdata;
SELECT * FROM bonddata;

SELECT DISTINCT PARTYNAME, SUM(DENOMINATION) AS TOTAL
 FROM receiverdata AS R
LEFT JOIN bonddata AS B
USING (UNIQUE_KEY)
GROUP BY PartyName;

WITH CASH AS(
SELECT PartyName, 
(SELECT DENOMINATION FROM BONDDATA WHERE BONDDATA.UNIQUE_KEY=receiverdata.UNIQUE_KEY
) AS DENOMINATIONS 
FROM  receiverdata ) 
SELECT PARTYNAME,SUM(DENOMINATIONS) FROM CASH
WHERE DENOMINATIONS = (SELECT MAX(DENOMINATIONS) FROM CASH)
GROUP BY PARTYNAME;
#JAMMU AND KASHMIR NATIONAL CONGRESS RECIEVED LEAST AMONG THE PARTIES WITH  RS 50000000
# 	BHARATHEY JANATHA PARTY RECIEVED HIGHEST CASH AMONG ALL THE PERTIES WITH RS 60605111000

/*10. Which political party received the highest number of electoral bonds?*/ 

# USING CTE'S
WITH NO_OF_BONDS AS( 
SELECT PARTYNAME,COUNT(*) AS TOTAL_BONDS
FROM receiverdata AS R
LEFT JOIN bonddata AS B 
USING (UNIQUE_KEY) 
GROUP BY PartyName)
SELECT *  FROM NO_OF_BONDS
WHERE TOTAL_BONDS=(SELECT MAX(TOTAL_BONDS) FROM NO_OF_BONDS);
## BHARATIYA JANATA PARTY  RECIEVED 8633 OF BONDS.

/*11. Which political party received the least cash?*/
SELECT * FROM receiverdata;
SELECT* FROM bonddata;

WITH CASH AS ( 
SELECT PartyName, SUM(Denomination) AS CASH_OBTAINED
FROM receiverdata AS R
LEFT JOIN bonddata AS B
ON R.Unique_key =B.Unique_key
GROUP BY PartyName) 
SELECT * FROM CASH 
WHERE CASH_OBTAINED=(SELECT MIN(CASH_OBTAINED) FROM CASH);

# GOA FORWARD PARTY RECIEVES THE LEAST CASH WITH 3500000.


/* 12. Which political party received the least number of electoral bonds?*/

SELECT * FROM receiverdata;
SELECT * FROM bonddata;

WITH BONDS AS( 
SELECT PartyName, COUNT(PartyName) AS NO_OF_BONDS FROM receiverdata AS R
GROUP  BY PartyName)
SELECT * FROM BONDS
WHERE NO_OF_BONDS=(SELECT MIN(NO_OF_BONDS) FROM BONDS);

# JAMMU AND KASHMIR NATIONAL CONFERENCE PARTY RECIEVES THE LEAST NO OF BONDS  WITH 5 IN NUMBER


/*13. Find the 2nd highest donor in terms of amount he paid?*/
SELECT * FROM donordata;
select * FROM bonddata;

SELECT PURCHASER, MAX(SECONDHIGH) FROM (
WITH SECOND_DONOR AS (
SELECT Purchaser,SUM(DENOMINATION) AS CASH FROM donordata AS D
LEFT JOIN bonddata AS B
ON D.Unique_key= B.Unique_key
GROUP BY Purchaser
ORDER BY CASH DESC
)
SELECT purchaser,max(cash) as secondhigh
 FROM SECOND_DONOR
 Where  Cash<(select max(cash) from second_donor)
 group by 1
 order by cash desc) AS HIGHER
 GROUP BY PURCHASER
;



WITH SECOND_DONOR AS (
SELECT Purchaser,SUM(DENOMINATION) AS CASH ,
dense_rank() over (order by sum(DENOMINATION) desc) as ranks FROM donordata AS D
LEFT JOIN bonddata AS B
ON D.Unique_key= B.Unique_key
GROUP BY Purchaser
ORDER BY CASH DESC
)
SELECT Purchaser,CASH
 FROM SECOND_DONOR
 Where  ranks=2;
#Megha Engineering and Infrastructures privatee limited back the 2nd donor for electrol bonds.

/* 14. Find the party which received the second highest donations?*/

SELECT * FROM receiverdata;
SELECT * FROM bonddata;
WITH HIGHEST_BONDS AS ( 
SELECT PartyName, SUM(DENOMINATION) AS CASH ,
DENSE_RANK() OVER (ORDER BY SUM(DENOMINATION) DESC ) AS RANKS FROM receiverdata  AS R
LEFT JOIN bonddata AS B 
ON R.Unique_key= B.Unique_key
GROUP BY PartyName
)
SELECT PARTYNAME,CASH
 FROM HIGHEST_BONDS 
 Where  ranks=2;
#ALL INDIA TRINAMOOL CONGRESS RECIEVED  2ND `HIGHEST DENOMINATIONS WITH RS 16095314000



/*15. Find the party which received the second highest number of bonds?*/

SELECT * FROM receiverdata;
SELECT * FROM bonddata;

WITH BONDS AS ( 
SELECT PartyName, COUNT(PartyName) AS NO_OF_BONDS,
DENSE_RANK() OVER(ORDER BY COUNT(PartyName) DESC) AS RANKS FROM  receiverdata AS R 
GROUP BY PartyName
)
SELECT PartyName,NO_OF_BONDS
FROM BONDS
WHERE RANKS=2
;

#ALL INDIA TRINAMOOL CONGRESS RECIEVES THE 2ND LARGEST PARTY TO RECIEVE HIGHEST NO OF BONDS WITH 3305 .

/*16. In which city were the most number of bonds purchased?*/
SELECT * FROM bankdata;
SELECT * FROM donordata;

WITH PURCHASE AS (
SELECT DISTINCT(CITY), COUNT(PURCHASER) AS NO_OF_BONDS  FROM donordata AS D
RIGHT JOIN bankdata AS B
ON D.PayBranchCode= B.branchCodeNo
GROUP BY CITY
ORDER BY NO_OF_BONDS DESC
)
SELECT * FROM PURCHASE
WHERE NO_OF_BONDS=( SELECT MAX(NO_OF_BONDS) FROM PURCHASE);
#Kolkata RECIEVED MORE NO OF BONDS WITH 5420


/* 17. In which city was the highest amount spent on electoral bonds?*/
SELECT * FROM donordata;
SELECT * FROM bonddata;
SELECT * FROM bankdata;

WITH SPEND AS (
SELECT PAYBRANCHCODE,DENOMINATION FROM DONORDATA AS D
JOIN BONDDATA AS B
ON D.UNIQUE_KEY=B.UNIQUE_KEY),
BOND1 AS( SELECT * FROM SPEND),
BOND2 AS (SELECT CITY,SUM(DENOMINATION) AS SPEND_CASH FROM BOND1
			JOIN BANKDATA AS BAN
            ON BOND1.PAYBRANCHCODE=BAN.BRANCHCODENO
            GROUP BY CITY)
SELECT  CITY , SPEND_CASH FROM BOND2
WHERE SPEND_CASH= (SELECT MAX(SPEND_CASH) FROM BOND2);
# HYDERABAD RECIEVED HIGHEST SPEND CASH WITH 29189070000

 
 /*18. In which city were the least number of bonds purchased?*/
 SELECT * FROM donordata;
 select * FROM bankdata;
 WITH BONDS AS (
SELECT DISTINCT(CITY)AS "CITY", COUNT(Unique_key) AS "NO_OF_BONDS"FROM bankdata AS B
RIGHT JOIN donordata AS D
ON B.branchCodeNo =D.PayBranchCode
GROUP BY B.CITY)
SELECT * FROM BONDS 
WHERE NO_OF_BONDS=(SELECT MIN(NO_OF_BONDS) FROM BONDS);
# RANCHI CITY PURCHASEDD LEAST NO OF BONDS WITH 5

/*19. In which city were the most number of bonds enchased?*/
SELECT * FROM receiverdata;
WITH RECIEVED AS (
SELECT DISTINCT (CITY) AS "CITY", COUNT(Unique_key) AS "NO_OF_BONDS" FROM receiverdata AS R
LEFT JOIN bankdata AS B 
ON R.PayBranchCode= B.branchCodeNo
GROUP BY CITY )
SELECT * FROM RECIEVED 
WHERE NO_OF_BONDS=(SELECT MAX(NO_OF_BONDS) FROM RECIEVED);
# NEW DELHI  IS THE CITY WHICH HAS HIGHEST NO OF RATE OF ENCASH MENT.

/*20.In which city were the least number of bonds enchased? */
WITH RECIEVED AS (
SELECT DISTINCT(CITY) AS "CITY", COUNT(Unique_key) AS "NO_OF_BONDS_ENCHASED" FROM receiverdata  AS R
LEFT JOIN bankdata AS B
ON R.PayBranchCode=B.branchCodeNo
GROUP BY CITY )
SELECT * FROM RECIEVED
WHERE NO_OF_BONDS_ENCHASED=(SELECT MIN(NO_OF_BONDS_ENCHASED) FROM RECIEVED);
#SRINAGAR HAS THE LEAST NO OF BONDS ENCHASED WITH 5 

/*21. List the branches where no electoral bonds were bought; if none, mention it as null.*/
SELECT * FROM donordata;
SELECT * FROM bankdata;

# TOFIND THE LIST OF BRANCHES WHERE NO ELECTRO BONDS ARE ENCHASED
WITH ENCASH AS( 
SELECT CITY,BRANCHCODENO FROM BANKDATA AS B 
LEFT JOIN RECEIVERDATA AS R
ON B.BRANCHCODENO= R.PAYBRANCHCODE
WHERE R.PARTYNAME IS NULL)
SELECT * FROM ENCASH 
;
#THERE ARE 16 BRANCHES WHERE NO ELECTROL BONDS ARE ENCASHED.

# TO FIND THE LIST OF BRANCHES WHERE NO ELECTRO BONDS ARE PURCHASED.
SELECT * FROM BANKDATA;
SELECT * FROM DONORDATA;
WITH PURCHASE AS (
SELECT 	BRANCHCODENO,CITY FROM BANKDATA AS BAN
LEFT JOIN DONORDATA AS D
ON BAN.BRANCHCODENO=D.PAYBRANCHCODE
WHERE D.PURCHASER IS NULL)
SELECT  CITY, BRANCHCODENO FROM PURCHASE;

#THERE ARE 10 BRANCHES WHERE NO ELECTROL BONDS ARE PURCHASED.



/* 22. Break down how much money is spent on electoral bonds for each year.*/
SELECT * FROM donordata;

SELECT * FROM bonddata;
#MONEY SPEND ON ELECTROL BONDS IN EVERY YEAR BY THE DONORS.
SELECT YEAR(PURCHASEDATE), SUM( DENOMINATION) AS "MONEY_SPEND" FROM DONORDATA AS D
LEFT JOIN BONDDATA AS B
USING(UNIQUE_KEY)
GROUP  BY YEAR(PURCHASEDATE)
ORDER BY YEAR(PURCHASEDATE);

SELECT * FROM receiverdata;
#MONEY SPEND ON ELECTROL BONDS IN EVERY YEAR BY THE RECIEVERS.
SELECT YEAR(DATEENCASHMENT),SUM(DENOMINATION) AS "SPEND_MONEY" FROM RECEIVERDATA AS R
LEFT JOIN  BONDDATA AS B
USING (UNIQUE_KEY)
GROUP BY YEAR(DATEENCASHMENT)
ORDER  BY YEAR(DATEENCASHMENT);




 /*23. Break down how much money is spent on electoral bonds for each year and provide the year and the amount. Provide values
for the highest and least year and amount.*/


WITH HIGH AS (
SELECT YEAR(PURCHASEDATE), SUM( DENOMINATION) AS "HIGHEST_MONEY_SPEND" FROM DONORDATA AS D
LEFT JOIN BONDDATA AS B
USING(UNIQUE_KEY)
GROUP  BY YEAR(PURCHASEDATE))
SELECT * FROM HIGH WHERE 
HIGHEST_MONEY_SPEND=(SELECT MAX(HIGHEST_MONEY_SPEND) FROM HIGH);

WITH  LOW AS (
SELECT YEAR(PURCHASEDATE), SUM( DENOMINATION) AS "LEAST_MONEY_SPEND" FROM DONORDATA AS D
LEFT JOIN BONDDATA AS B
USING(UNIQUE_KEY)
GROUP  BY YEAR(PURCHASEDATE))
SELECT * FROM LOW WHERE 
LEAST_MONEY_SPEND=(SELECT MIN(LEAST_MONEY_SPEND) FROM LOW);

#HIGHEST MONEY SPEND IN THE YEAR 2023 WITH RS 42464745000 BY THE DONOR
#LEAST MONEY SPEND IN THE YEAR 2020 WITH RS 3639601000 BY THE DONOR


/*24. Find out how many donors bought the bonds but did not donate to any political party?*/
SELECT * FROM donordata;
SELECT * FROM receiverdata;
SELECT COUNT(D.UNIQUE_KEY) AS "DONOR" FROM donordata AS D
LEFT JOIN receiverdata AS R
ON D.Unique_key=R.Unique_key
WHERE  R.UNIQUE_KEY IS NULL
;
# THERE ARE  130 DONOR BOUGHT THE BONDS BUT THEY DIDNOT DONATE TO ANY PPOLITICAL PARTY.


/*25. Find out the money that could have gone to the PM Office, assuming the above question assumption (Domain Knowledge)*/
SELECT * FROM bonddata;
SELECT * FROM DONORDATA;
SELECT * FROM RECEIVERDATA;


WITH PN AS ( 
SELECT D.UNIQUE_KEY  FROM DONORDATA AS D
LEFT JOIN RECEIVERDATA AS R
USING(UNIQUE_KEY)
WHERE R.UNIQUE_KEY IS NULL)
 SELECT SUM(DENOMINATION) AS PM_RELIEF_FUND FROM BONDDATA AS B
JOIN PN 
USING(UNIQUE_KEY);



/*26. Find out how many bonds don't have donors associated with them.*/
SELECT * FROM receiverdata;
SELECT * FROM donordata;
SELECT COUNT(PartyName) AS "DONOR_LESS_BONDS" from receiverdata as R 
LEFT  JOIN donordata AS D
ON R.Unique_key=D.Unique_key
WHERE Purchaser IS NULL;
# THERE ARE 1680 BONDS WHICH DONOT HAVE DONORS.

/*27. Pay Teller is the employee ID who either created the bond or redeemed it. So find the employee ID who issued the highest
number of bonds.*/
# PAYTELLER ISSUED BONDS IN THE DONATION SIDE
SELECT * FROM DONORDATA;
WITH  DONOR AS ( 
SELECT PAYTELLER,COUNT(*) AS "NO_OF_BONDS" FROM DONORDATA
GROUP BY PAYTELLER
ORDER BY NO_OF_BONDS DESC
)
SELECT * FROM DONOR 
WHERE NO_OF_BONDS=(SELECT MAX(NO_OF_BONDS) FROM DONOR);
# 6405134 IS THE ONLY  PAYTELLER WHO IS RESPONSIBLE FOR THE 1946 BONDS.

#PAYTELLER  ISSUED BONDS IN THE RECIEVER SIDE 
WITH  RECIEVE AS ( 
SELECT PAYTELLER,COUNT(*) AS "NO_OF_BONDS" FROM RECEIVERDATA
GROUP BY PAYTELLER
ORDER BY NO_OF_BONDS DESC
)
SELECT * FROM RECIEVE 
WHERE NO_OF_BONDS=(SELECT MAX(NO_OF_BONDS) FROM RECIEVE);
# 3645 BONDS ARE ISSUED BY THE 7516991 PAYTELLER

/*28. Find the employee ID who issued the least number of bonds.*/

#USING CTE'S:

WITH DONATE AS (
SELECT PAYTELLER ,COUNT(*) AS "LEAST_NO_OF_BONDS" FROM donordata AS D
GROUP BY PayTeller
ORDER BY PAYTELLER)
SELECT * FROM DONATE 
WHERE LEAST_NO_OF_BONDS=(SELECT MIN(LEAST_NO_OF_BONDS) FROM DONATE);
#5575761 AND 5578876 ARE THE TWO PAYTELLER NUMBERS MAKE LEAST NO OF BONDS FROM THE DONOR SIDE WITH 1 BOND.

WITH ACQUIRE AS (
SELECT PAYTELLER ,COUNT(*) AS "LEAST_NO_OF_BONDS" FROM RECEIVERDATA AS R
GROUP BY PayTeller
ORDER BY PAYTELLER)
SELECT * FROM ACQUIRE
WHERE LEAST_NO_OF_BONDS=(SELECT MIN(LEAST_NO_OF_BONDS) FROM ACQUIRE);

#5880793 , 6596169, 7626436 ARE THE THREELEAST INVOLVING EMPLOYEES IN THE ENCASHMENT OF MONEY IN THE RECIEVER SIDE WITH 3 BONDS.


#USING SUB-QUERIES.
SELECT PAYTELLER
FROM (
    SELECT PAYTELLER, COUNT(*) AS bond_count
    FROM donordata
    GROUP BY PAYTELLER
) AS bond_counts
WHERE bond_count = (
    SELECT MIN(bond_count)
    FROM (
        SELECT PAYTELLER, COUNT(*) AS bond_count
        FROM donordata
        GROUP BY PayTeller
    ) AS min_bond_counts
);

/*29. Find the employee ID who assisted in redeeming or enchasing bonds the most.*/

#DONOR SIDE
WITH DONOR AS ( SELECT PAYTELLER ,COUNT(*) AS "MOST_BONDS" FROM DONORDATA AS D
GROUP BY PAYTELLER
ORDER BY COUNT(PAYTELLER))
SELECT * FROM DONOR 
WHERE MOST_BONDS =(SELECT MAX(MOST_BONDS) FROM DONOR);
# PAYTELLER HAVING EMPLOYEE iD  6405134 REDEEEMING AT DONOR SIDE WITH 1946 BONDS.

WITH RECIEVE AS ( SELECT PAYTELLER ,COUNT(*) AS "MOST_BONDS" FROM RECEIVERDATA AS R
GROUP BY PAYTELLER
ORDER BY COUNT(PAYTELLER))
SELECT * FROM RECIEVE 
WHERE MOST_BONDS =(SELECT MAX(MOST_BONDS) FROM RECIEVE);
# PAYTELLER WITH 7516991 ENCASH 3645 BONDS FROM THE RECIEVER END.

/*  30. Find the employee ID who assisted in redeeming or enchasing bonds the least */

WITH EMP AS (
SELECT  PAYTELLER, COUNT( PAyteller) AS "NO_OF_BONDS" FROM RECEIVERDATA AS R
GROUP BY PAYTELLER
)
SELECT * FROM EMP
WHERE NO_OF_BONDS =(SELECT MIN(NO_OF_BONDS) FROM EMP);



/*********** FURTHER QUERIES***************/

#1. Tell me total how many bonds are created?
SELECT * FROM DONORDATA;
SELECT * FROM RECEIVERDATA;
#TOTAL NO OF KEYS CREATED = DONOR SIDE KEYS + UNACCOUNTED KEYS 

WITH DONOR AS( 
SELECT UNIQUE_KEY AS DONOR_KEYS FROM DONORDATA ),
UNACCOUNTED AS (SELECT * FROM DONOR AS D
RIGHT JOIN  RECEIVERDATA AS R
ON D.DONOR_KEYS=R.UNIQUE_KEY),
UNACCOUNTED1 AS (
SELECT UNIQUE_KEY AS "UNACCOUNTED" FROM UNACCOUNTED
WHERE DONOR_KEYS IS NULL),
TOTAL AS (SELECT * FROM UNACCOUNTED1
			union all
            SELECT * FROM DONOR )
SELECT COUNT( * ) AS "TOTAL KEYS GENERATED"  FROM TOTAL;
#THERE ARE 20551 UNIQUE KEYS GENERATED 

/*2. Find the count of Unique Denominations provided by SBI?*/
SELECT * FROM BONDDATA;
SELECT COUNT(DISTINCT (DENOMINATION)) AS NO_OF_DENOMINATIONS FROM BONDDATA ;


#THERE ARE 5 DISTINCT DENOMINATION PROVIDED BY SBI

/*3. List all the unique denominations that are available?*/
SELECT DISTINCT(DENOMINATION) FROM BONDDATA
ORDER BY DENOMINATION;
#THESE ARE THE LIST OF DINOMINATIONS  FROM SBI

/*4. Total money received by the bank for selling bonds*/
SELECT * FROM RECEIVERDATA;

SELECT SUM( DENOMINATION)  AS "TOTAL_DENOMINATION_FROM_BANK" FROM DONORDATA AS R
LEFT JOIN BONDDATA AS B
USING( UNIQUE_KEY);

#121555132000 RS RECIEVED AFTER SELLING BONDS .


/*5. Find the count of bonds for each denominations that are created.*/

SELECT DISTINCT(DENOMINATION) AS DENOMINATION, COUNT(UNIQUE_KEY) AS "NO_OF_BONDS" FROM BONDDATA AS B
RIGHT JOIN DONORDATA AS D
USING(UNIQUE_KEY)
GROUP BY DENOMINATION
ORDER BY DENOMINATION;

/*THESE ARE THE COUNT OF BONDS WITH RESPECT OT THEIR DENOMINATIONS
1000	132
10000	220
100000	2228
1000000	4620
10000000	11671
*/

/*6. Find the count and Amount or Valuation of electoral bonds for each denominations.*/
SELECT DISTINCT(DENOMINATION) AS DENOMINATION, COUNT(unique_key) as "NO_OF_BONDS",SUM(DENOMINATION) AS AMOUNT FROM BONDDATA AS B
RIGHT JOIN DONORDATA AS D
USING(UNIQUE_KEY)
GROUP BY DENOMINATION
ORDER BY DENOMINATION;

/* THESE ARE THE TOTAL AMOUNT WITH THE NO OF BONDS TO THE RESPECTIVE DENOMINATIONS.
1000		132		132000
10000		220		2200000
100000		2228	222800000
1000000		4620	4620000000
10000000	11671	116710000000 
*/

/*7. Number of unique bank branches where we can buy electoral bond?*/
SELECT DISTINCT(COUNT( BRANCHCODENO)) AS BRANCHES FROM BANKDATA ;

# THERE ARE 29 BRANCHES FROM WHICH WE CAN ABLE TO BUY THE ELECTROL BONDS.

/* 8. How many companies bought electoral bonds*/
SELECT COUNT(DISTINCT(PURCHASER)) AS NO_OF_COMPANIES FROM DONORDATA;
# THERE ARE 1228 DISTINCT COMPANIES BOUGHT ELECTORAL BONDS.

/*9. How many companies made political donations*/
WITH COMPANIES AS (
SELECT PURCHASER ,D.UNIQUE_KEY AS "DONOR_KEY" ,R.UNIQUE_KEY AS "RECEIVER_KEY" FROM DONORDATA AS D
JOIN receiverdata AS R
USING (UNIQUE_KEY))
SELECT COUNT(DISTINCT(PURCHASER)) FROM COMPANIES;
# 1205 COMPANIES MADE POLITICAL DONATIONS.

/* 10. How many number of parties received donations*/
SELECT COUNT(DISTINCT(PARTYNAME)) AS NO_OF_PARTIES FROM donordata AS D
JOIN receiverdata AS R
USING (UNIQUE_KEY);
# THERE ARE 23 PARTIES RECIEVED DONATIONS.

SELECT COUNT(DISTINCT(PARTYNAME)) AS NO_OF_PARTIES FROM receiverdata;
#THERE ARE 24 PARTIES WHO RECIEVED DONATIONS

/* 11. List all the political parties that received donations */
SELECT DISTINCT(PARTYNAME) FROM RECEIVERDATA ;
/*BHARAT RASHTRA SAMITHI
PRESIDENT, ALL INDIA CONGRESS COMMITTEE
ALL INDIA TRINAMOOL CONGRESS
BHARATIYA JANATA PARTY
SHIVSENA
BIJU JANATA DAL
TELUGU DESAM PARTY
AAM AADMI PARTY
DRAVIDA MUNNETRA KAZHAGAM (DMK)
SIKKIM KRANTIKARI MORCHA
YSR CONGRESS PARTY (YUVAJANA SRAMIKA RYTHU CONGRESS PARTY)
NATIONALIST CONGRESS PARTY MAHARASHTRA PRADESH
JHARKHAND MUKTI MORCHA
JANASENA PARTY
RASHTRIYA JANTA DAL
JANATA DAL ( SECULAR )
SIKKIM DEMOCRATIC FRONT
ADYAKSHA SAMAJVADI PARTY
BIHAR PRADESH JANTA DAL(UNITED)
ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM
SHIROMANI AKALI DAL
GOA FORWARD PARTY
MAHARASHTRAWADI GOMNTAK PARTY
JAMMU AND KASHMIR NATIONAL CONFERENCE */

/*12. What is the average amount that each political party received */
WITH RECIEVED AS (
SELECT PARTYNAME, SUM(DENOMINATION) AS MONEY FROM receiverdata AS R
LEFT JOIN BONDDATA AS B
USING( UNIQUE_KEY)
GROUP BY PartyName)
SELECT AVG(MONEY) AS AVERAGE_MONEY_RECEIVED FROM RECIEVED;
# AVERAGE AMOUNT RECEIVED BY EACH POLITOCAL PARTY IS  RS 5320453875

/*13. What is the average bond value produced by bank*/
WITH VALUE_BOND AS (
SELECT  DISTINCT(PURCHASER),SUM(DENOMINATION) AS MONEY FROM DONORDATA  
LEFT JOIN BONDDATA 
USING (UNIQUE_KEY)
GROUP BY PURCHASER)
SELECT AVG(MONEY) FROM VALUE_BOND;
# AVERAGE BOND VALUE PRODUCED BY THE BANK IS  RS 98986263.8436

/*14. List the political parties which have enchased bonds in different cities?*/
SELECT * FROM RECEIVERDATA ;
SELECT * FROM BANKDATA;
SELECT PARTYNAME, COUNT(DISTINCT(PAYBRANCHCODE))  AS "ENCASHED_BRANCH"  FROM receiverdata AS R
GROUP BY PARTYNAME 
HAVING ENCASHED_BRANCH>1;
 #THERE ARE 2 PARTIES WHO ENCASHED IN DIFFERENT CITIES.
 











